const data = [
  {
    player_id: 633,
    position_id: 1,
    number: 22,
    injured: false,
    minutes: 180,
    appearences: 2,
    lineups: 2,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 13,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 633,
        team_id: 8,
        country_id: 556,
        position_id: 1,
        common_name: 'S. Mignolet',
        fullname: 'Simon Mignolet',
        firstname: 'Simon',
        lastname: 'Mignolet',
        nationality: 'Belgium',
        birthdate: '06/03/1988',
        birthcountry: 'Belgium',
        birthplace: 'Sint-Truiden',
        height: '193 cm',
        weight: '87 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/25/633.png',
      },
    },
    position: { data: { id: 1, name: 'Goalkeeper' } },
  },
  {
    player_id: 1917,
    position_id: 2,
    number: 66,
    injured: false,
    minutes: 975,
    appearences: 12,
    lineups: 11,
    substitute_in: 1,
    substitute_out: 4,
    substitutes_on_bench: 3,
    goals: 2,
    assists: 1,
    yellowcards: 3,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1917,
        team_id: 8,
        country_id: 462,
        position_id: 2,
        common_name: 'T. Alexander-Arnold',
        fullname: 'Trent Alexander-Arnold',
        firstname: 'Trent',
        lastname: 'Alexander-Arnold',
        nationality: 'England',
        birthdate: '07/10/1998',
        birthcountry: 'England',
        birthplace: 'Liverpool',
        height: '175 cm',
        weight: '69 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/29/1917.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1920,
    position_id: 2,
    number: 32,
    injured: false,
    minutes: 645,
    appearences: 8,
    lineups: 7,
    substitute_in: 1,
    substitute_out: 0,
    substitutes_on_bench: 1,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1920,
        team_id: 8,
        country_id: 593,
        position_id: 2,
        common_name: 'J. Matip',
        fullname: 'Joël Andre Job Matip',
        firstname: 'Joël Andre',
        lastname: 'Job Matip',
        nationality: 'Cameroon',
        birthdate: '08/08/1991',
        birthcountry: 'Germany',
        birthplace: 'Bochum',
        height: '195 cm',
        weight: '90 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/0/1920.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1168,
    position_id: 2,
    number: 6,
    injured: false,
    minutes: 1230,
    appearences: 14,
    lineups: 14,
    substitute_in: 0,
    substitute_out: 1,
    substitutes_on_bench: 0,
    goals: 0,
    assists: 1,
    yellowcards: 2,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1168,
        team_id: 8,
        country_id: 266,
        position_id: 2,
        common_name: 'D. Lovren',
        fullname: 'Dejan Lovren',
        firstname: 'Dejan',
        lastname: 'Lovren',
        nationality: 'Croatia',
        birthdate: '05/07/1989',
        birthcountry: 'Bosnia and Herzegovina',
        birthplace: 'Zenica',
        height: '188 cm',
        weight: '84 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/16/1168.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1471,
    position_id: 2,
    number: 18,
    injured: false,
    minutes: 743,
    appearences: 10,
    lineups: 9,
    substitute_in: 1,
    substitute_out: 2,
    substitutes_on_bench: 6,
    goals: 0,
    assists: 3,
    yellowcards: 2,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1471,
        team_id: 8,
        country_id: 32,
        position_id: 2,
        common_name: 'Alberto Moreno',
        fullname: 'Alberto Moreno Pérez',
        firstname: 'Alberto',
        lastname: 'Moreno Pérez',
        nationality: 'Spain',
        birthdate: '05/07/1992',
        birthcountry: 'Spain',
        birthplace: 'Sevilla',
        height: '171 cm',
        weight: '65 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/31/1471.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1388,
    position_id: 3,
    number: 23,
    injured: false,
    minutes: 696,
    appearences: 10,
    lineups: 8,
    substitute_in: 2,
    substitute_out: 4,
    substitutes_on_bench: 2,
    goals: 3,
    assists: 0,
    yellowcards: 4,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1388,
        team_id: 8,
        country_id: 11,
        position_id: 3,
        common_name: 'E. Can',
        fullname: 'Emre Can',
        firstname: 'Emre',
        lastname: 'Can',
        nationality: 'Germany',
        birthdate: '12/01/1994',
        birthcountry: 'Germany',
        birthplace: 'Frankfurt am Main',
        height: '184 cm',
        weight: '82 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/12/1388.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 323,
    position_id: 3,
    number: 14,
    injured: false,
    minutes: 1021,
    appearences: 12,
    lineups: 11,
    substitute_in: 1,
    substitute_out: 2,
    substitutes_on_bench: 3,
    goals: 0,
    assists: 1,
    yellowcards: 4,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 323,
        team_id: 8,
        country_id: 462,
        position_id: 3,
        common_name: 'J. Henderson',
        fullname: 'Jordan Brian Henderson',
        firstname: 'Jordan Brian',
        lastname: 'Henderson',
        nationality: 'England',
        birthdate: '17/06/1990',
        birthcountry: 'England',
        birthplace: 'Sunderland',
        height: '182 cm',
        weight: '67 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/3/323.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 1365,
    position_id: 3,
    number: 5,
    injured: false,
    minutes: 1029,
    appearences: 14,
    lineups: 11,
    substitute_in: 3,
    substitute_out: 2,
    substitutes_on_bench: 3,
    goals: 1,
    assists: 2,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1365,
        team_id: 8,
        country_id: 38,
        position_id: 3,
        common_name: 'G. Wijnaldum',
        fullname: 'Georginio Wijnaldum',
        firstname: 'Georginio',
        lastname: 'Wijnaldum',
        nationality: 'Netherlands',
        birthdate: '11/11/1990',
        birthcountry: 'Netherlands',
        birthplace: 'Rotterdam',
        height: '175 cm',
        weight: '69 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/21/1365.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 4125,
    position_id: 4,
    number: 11,
    injured: false,
    minutes: 1112,
    appearences: 15,
    lineups: 14,
    substitute_in: 1,
    substitute_out: 8,
    substitutes_on_bench: 1,
    goals: 11,
    assists: 4,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 4125,
        team_id: 8,
        country_id: 886,
        position_id: 4,
        common_name: 'Mohamed Salah',
        fullname: 'Mohamed  Salah Ghaly',
        firstname: 'Mohamed',
        lastname: 'Salah Ghaly',
        nationality: 'Egypt',
        birthdate: '15/06/1992',
        birthcountry: 'Egypt',
        birthplace: 'Muḥāfaẓat al Gharbiyya',
        height: '175 cm',
        weight: '71 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/29/4125.png',
      },
    },
    position: { data: { id: 4, name: 'Attacker' } },
  },
  {
    player_id: 1461,
    position_id: 4,
    number: 9,
    injured: false,
    minutes: 1230,
    appearences: 15,
    lineups: 15,
    substitute_in: 0,
    substitute_out: 10,
    substitutes_on_bench: 0,
    goals: 11,
    assists: 10,
    yellowcards: 2,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1461,
        team_id: 8,
        country_id: 5,
        position_id: 4,
        common_name: 'Roberto Firmino',
        fullname: 'Roberto Firmino Barbosa de Oliveira',
        firstname: 'Roberto Firmino',
        lastname: 'Barbosa de Oliveira',
        nationality: 'Brazil',
        birthdate: '02/10/1991',
        birthcountry: 'Brazil',
        birthplace: 'Maceió',
        height: '181 cm',
        weight: '76 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/21/1461.png',
      },
    },
    position: { data: { id: 4, name: 'Attacker' } },
  },
  {
    player_id: 1389,
    position_id: 4,
    number: 19,
    injured: false,
    minutes: 1117,
    appearences: 13,
    lineups: 13,
    substitute_in: 0,
    substitute_out: 6,
    substitutes_on_bench: 0,
    goals: 10,
    assists: 3,
    yellowcards: 2,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1389,
        team_id: 8,
        country_id: 200,
        position_id: 4,
        common_name: 'S. Mané',
        fullname: 'Sadio Mané',
        firstname: 'Sadio',
        lastname: 'Mané',
        nationality: 'Senegal',
        birthdate: '10/04/1992',
        birthcountry: 'Senegal',
        birthplace: 'Sedhiou',
        height: '175 cm',
        weight: '69 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/13/1389.png',
      },
    },
    position: { data: { id: 4, name: 'Attacker' } },
  },
  {
    player_id: 4817,
    position_id: 1,
    number: 1,
    injured: false,
    minutes: 1170,
    appearences: 13,
    lineups: 13,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 2,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 4817,
        team_id: 8,
        country_id: 11,
        position_id: 1,
        common_name: 'L. Karius',
        fullname: 'Loris Karius',
        firstname: 'Loris',
        lastname: 'Karius',
        nationality: 'Germany',
        birthdate: '22/06/1993',
        birthcountry: 'Germany',
        birthplace: 'Biberach an der Riß',
        height: '189 cm',
        weight: '75 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/17/4817.png',
      },
    },
    position: { data: { id: 1, name: 'Goalkeeper' } },
  },
  {
    player_id: 1453,
    position_id: 2,
    number: 12,
    injured: false,
    minutes: 398,
    appearences: 6,
    lineups: 4,
    substitute_in: 2,
    substitute_out: 0,
    substitutes_on_bench: 5,
    goals: 0,
    assists: 0,
    yellowcards: 1,
    yellowred: 1,
    redcards: 0,
    player: {
      data: {
        player_id: 1453,
        team_id: 8,
        country_id: 462,
        position_id: 2,
        common_name: 'J. Gomez',
        fullname: 'Joe Gomez',
        firstname: 'Joe',
        lastname: 'Gomez',
        nationality: 'England',
        birthdate: '23/05/1997',
        birthcountry: 'England',
        birthplace: 'London',
        height: '188 cm',
        weight: '77 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/13/1453.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1906,
    position_id: 2,
    number: 17,
    injured: false,
    minutes: 304,
    appearences: 8,
    lineups: 3,
    substitute_in: 5,
    substitute_out: 0,
    substitutes_on_bench: 10,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1906,
        team_id: 8,
        country_id: 2405,
        position_id: 2,
        common_name: 'R. Klavan',
        fullname: 'Ragnar Klavan',
        firstname: 'Ragnar',
        lastname: 'Klavan',
        nationality: 'Estonia',
        birthdate: '30/10/1985',
        birthcountry: 'Estonia',
        birthplace: 'Viljandi',
        height: '187 cm',
        weight: '85 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/18/1906.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1918,
    position_id: 3,
    number: 16,
    injured: false,
    minutes: 10,
    appearences: 2,
    lineups: 0,
    substitute_in: 2,
    substitute_out: 0,
    substitutes_on_bench: 2,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1918,
        team_id: 69,
        country_id: 296,
        position_id: 3,
        common_name: 'M. Grujić',
        fullname: 'Marko Grujić',
        firstname: 'Marko',
        lastname: 'Grujić',
        nationality: 'Serbia',
        birthdate: '13/04/1996',
        birthcountry: 'Serbia',
        birthplace: 'Beograd',
        height: '191 cm',
        weight: '82 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/30/1918.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 197,
    position_id: 3,
    number: 7,
    injured: false,
    minutes: 928,
    appearences: 13,
    lineups: 9,
    substitute_in: 4,
    substitute_out: 1,
    substitutes_on_bench: 6,
    goals: 0,
    assists: 8,
    yellowcards: 1,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 197,
        team_id: 8,
        country_id: 462,
        position_id: 3,
        common_name: 'J. Milner',
        fullname: 'James Philip Milner',
        firstname: 'James Philip',
        lastname: 'Milner',
        nationality: 'England',
        birthdate: '04/01/1986',
        birthcountry: 'England',
        birthplace: 'Leeds',
        height: '175 cm',
        weight: '70 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/5/197.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 4203,
    position_id: 4,
    number: 29,
    injured: false,
    minutes: 49,
    appearences: 4,
    lineups: 0,
    substitute_in: 4,
    substitute_out: 0,
    substitutes_on_bench: 11,
    goals: 0,
    assists: 0,
    yellowcards: 1,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 4203,
        team_id: 8,
        country_id: 462,
        position_id: 4,
        common_name: 'D. Solanke',
        fullname: 'Dominic Solanke',
        firstname: 'Dominic',
        lastname: 'Solanke',
        nationality: 'England',
        birthdate: '14/09/1997',
        birthcountry: 'England',
        birthplace: 'Reading',
        height: '187 cm',
        weight: '80 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/11/4203.png',
      },
    },
    position: { data: { id: 4, name: 'Attacker' } },
  },
  {
    player_id: 1078,
    position_id: 2,
    number: 26,
    injured: false,
    minutes: 540,
    appearences: 6,
    lineups: 6,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 3,
    goals: 0,
    assists: 0,
    yellowcards: 1,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1078,
        team_id: 8,
        country_id: 1161,
        position_id: 2,
        common_name: 'A. Robertson',
        fullname: 'Andrew Robertson',
        firstname: 'Andrew',
        lastname: 'Robertson',
        nationality: 'Scotland',
        birthdate: '11/03/1994',
        birthcountry: 'Scotland',
        birthplace: 'Glasgow',
        height: '178 cm',
        weight: '64 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/22/1078.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 622,
    position_id: 4,
    number: 15,
    injured: false,
    minutes: 83,
    appearences: 5,
    lineups: 0,
    substitute_in: 5,
    substitute_out: 0,
    substitutes_on_bench: 7,
    goals: 1,
    assists: 2,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 622,
        team_id: 10,
        country_id: 462,
        position_id: 4,
        common_name: 'D. Sturridge',
        fullname: 'Daniel Andre Sturridge',
        firstname: 'Daniel Andre',
        lastname: 'Sturridge',
        nationality: 'England',
        birthdate: '01/09/1989',
        birthcountry: 'England',
        birthplace: 'Birmingham',
        height: '188 cm',
        weight: '76 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/14/622.png',
      },
    },
    position: { data: { id: 4, name: 'Attacker' } },
  },
  {
    player_id: 850,
    position_id: 3,
    number: 21,
    injured: false,
    minutes: 320,
    appearences: 7,
    lineups: 4,
    substitute_in: 3,
    substitute_out: 2,
    substitutes_on_bench: 7,
    goals: 2,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 850,
        team_id: 8,
        country_id: 462,
        position_id: 3,
        common_name: 'A. Oxlade-Chamberlain',
        fullname: 'Alex Oxlade-Chamberlain',
        firstname: 'Alex',
        lastname: 'Oxlade-Chamberlain',
        nationality: 'England',
        birthdate: '15/08/1993',
        birthcountry: 'England',
        birthplace: 'Portsmouth',
        height: '180 cm',
        weight: '70 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/18/850.png',
      },
    },
    position: { data: { id: 3, name: 'Midfielder' } },
  },
  {
    player_id: 978,
    position_id: 2,
    number: 38,
    injured: false,
    minutes: 0,
    appearences: 0,
    lineups: 0,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 1,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 978,
        team_id: 16,
        country_id: 462,
        position_id: 2,
        common_name: 'J. Flanagan',
        fullname: 'Jon Flanagan',
        firstname: 'Jon',
        lastname: 'Flanagan',
        nationality: 'England',
        birthdate: '01/01/1993',
        birthcountry: 'England',
        birthplace: 'Liverpool',
        height: '181 cm',
        weight: '79 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/18/978.png',
      },
    },
    position: { data: { id: 2, name: 'Defender' } },
  },
  {
    player_id: 1743,
    position_id: null,
    number: null,
    injured: false,
    minutes: 540,
    appearences: 6,
    lineups: 6,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 1,
    goals: 0,
    assists: 0,
    yellowcards: 1,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1743,
        team_id: 8,
        country_id: 38,
        position_id: 2,
        common_name: 'V. van Dijk',
        fullname: 'Virgil van Dijk',
        firstname: 'Virgil',
        lastname: 'van Dijk',
        nationality: 'Netherlands',
        birthdate: '08/07/1991',
        birthcountry: 'Netherlands',
        birthplace: 'Breda',
        height: '193 cm',
        weight: '92 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/15/1743.png',
      },
    },
  },
  {
    player_id: 1149,
    position_id: null,
    number: null,
    injured: false,
    minutes: 152,
    appearences: 2,
    lineups: 1,
    substitute_in: 1,
    substitute_out: 0,
    substitutes_on_bench: 2,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1149,
        team_id: 8,
        country_id: 462,
        position_id: 3,
        common_name: 'A. Lallana',
        fullname: 'Adam David Lallana',
        firstname: 'Adam David',
        lastname: 'Lallana',
        nationality: 'England',
        birthdate: '10/05/1988',
        birthcountry: 'England',
        birthplace: 'St Albans',
        height: '172 cm',
        weight: '73 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/29/1149.png',
      },
    },
  },
  {
    player_id: 1450,
    position_id: null,
    number: null,
    injured: false,
    minutes: 54,
    appearences: 4,
    lineups: 0,
    substitute_in: 4,
    substitute_out: 0,
    substitutes_on_bench: 6,
    goals: 0,
    assists: 1,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1450,
        team_id: 8,
        country_id: 462,
        position_id: 4,
        common_name: 'D. Ings',
        fullname: 'Daniel William John Ings',
        firstname: 'Daniel William John',
        lastname: 'Ings',
        nationality: 'England',
        birthdate: '23/07/1992',
        birthcountry: 'England',
        birthplace: 'Winchester',
        height: '178 cm',
        weight: '73 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/10/1450.png',
      },
    },
  },
  {
    player_id: 1202,
    position_id: null,
    number: null,
    injured: false,
    minutes: 12,
    appearences: 2,
    lineups: 0,
    substitute_in: 2,
    substitute_out: 0,
    substitutes_on_bench: 5,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 1202,
        team_id: 8,
        country_id: 462,
        position_id: 2,
        common_name: 'N. Clyne',
        fullname: 'Nathaniel Edwin Clyne',
        firstname: 'Nathaniel Edwin',
        lastname: 'Clyne',
        nationality: 'England',
        birthdate: '05/04/1991',
        birthcountry: 'England',
        birthplace: 'Stockwell',
        height: '175 cm',
        weight: '67 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/18/1202.png',
      },
    },
  },
  {
    player_id: 339015,
    position_id: null,
    number: null,
    injured: false,
    minutes: 0,
    appearences: 0,
    lineups: 0,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 1,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 339015,
        team_id: 8,
        country_id: 455,
        position_id: 2,
        common_name: 'C. Masterson',
        fullname: 'Conor Masterson',
        firstname: 'Conor',
        lastname: 'Masterson',
        nationality: 'Republic of Ireland',
        birthdate: '08/09/1998',
        birthcountry: 'Republic of Ireland',
        birthplace: 'Dublin',
        height: '185 cm',
        weight: '75 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/7/339015.png',
      },
    },
  },
  {
    player_id: 5193,
    position_id: null,
    number: null,
    injured: false,
    minutes: 0,
    appearences: 0,
    lineups: 0,
    substitute_in: 0,
    substitute_out: 0,
    substitutes_on_bench: 2,
    goals: 0,
    assists: 0,
    yellowcards: 0,
    yellowred: 0,
    redcards: 0,
    player: {
      data: {
        player_id: 5193,
        team_id: 8,
        country_id: 515,
        position_id: 3,
        common_name: 'B. Woodburn',
        fullname: 'Benjamin Woodburn',
        firstname: 'Benjamin',
        lastname: 'Woodburn',
        nationality: 'Wales',
        birthdate: '15/10/1999',
        birthcountry: 'England',
        birthplace: 'Chester',
        height: '174 cm',
        weight: '72 kg',
        image_path:
          'https://cdn.sportmonks.com/images/soccer/players/9/5193.png',
      },
    },
  },
]
function parseSquad(data) {
  if (!data.length) {
    return null
  }
  return data
    .map(playerData => {
      const name = playerData.player.data.fullname.split(' ')
      return {
        id: playerData.player_id,
        name: `${name[0]} ${name[name.length - 1]}`,
        position: playerData.position && playerData.position.data.name,
        appearences: playerData.appearences,
        goals: playerData.goals,
      }
    })
    .reduce((obj, player) => {
      if (!obj[player.position]) {
        obj[player.position] = [player]
      } else {
        obj[player.position].push(player)
      }
      return obj
    }, {})
}

export default parseSquad(data)
